version: "3"

services:
  web:
    container_name: theeye
    hostname: theeye
    build:
      context: .
    environment:
      - FLASK_APP=$FLASK_APP
      - FLASK_ENV=$FLASK_ENV
      - SQLALCHEMY_DATABASE_URI=$SQLALCHEMY_DATABASE_URI
      - SECRET_KEY=$SECRET_KEY
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
    - theeye
  db:
    image: postgres:latest
    container_name: theeye_db
    hostname: theeye_db
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_MULTIPLE_DATABASES: $POSTGRES_MULTIPLE_DATABASES
    volumes:
      - ./scripts/database:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - theeye


networks:
  theeye:
    driver: bridge
